/**
 *
 * Performer action types
 *
 */

export const ActionTypes = {
  DEFAULT_ACTION: 'app/performer/DEFAULT_ACTION',
  ALLOW_TO_DEVICES_STATUS: 'app/performer/ALLOW_TO_DEVICES_STATUS',
  UPDATE_SETTING_COMPONENT: 'app/performer/UPDATE_SETTING_COMPONENT',
  ALLOW_LIVE_PERFORMACE: 'app/performer/ALLOW_LIVE_PERFORMACE',
  STAGE_REQUEST: 'app/performer/STAGE_REQUEST',
  USER_STATE: 'app/performer/USER_STATE',
  REMOVE_USER_PERFORMANCE: 'app/performer/REMOVE_USER_PERFORMANCE',
  INVITE_AUDIENCE: 'app/performer/INVITE_AUDIENCE',
  RESET_PERFORMER_STATE: 'app/performer/RESET_PERFORMER_STATE',
  SET_ACTIVE_STAGE_USER: 'app/performer/SET_ACTIVE_STAGE_USER',
  SET_ACTIVE_INVITED_AUDIENCE: 'app/performer/SET_ACTIVE_INVITED_AUDIENCE',
  SET_ACTIVE_STAGE_AUDIENCE: 'app/performer/SET_ACTIVE_STAGE_AUDIENCE',
  START_RECORDING: 'app/performer/START_RECORDING',
  START_RECORDING_SUCCESS: 'app/performer/START_RECORDING_SUCCESS',
  STOP_RECORDING: 'app/performer/STOP_RECORDING',
  QUERY_RECORDING: 'app/performer/QUERY_RECORDING',
  QUERY_RECORDING_STATUS: 'app/performer/QUERY_RECORDING_STATUS',
  RECORDING_TOKEN: 'app/performer/RECORDING_TOKEN',
  SET_RECORDING_TOKEN: 'app/performer/SET_RECORDING_TOKEN',
};
