/**
 *
 * ProductCreate action types
 *
 */

export const ActionTypes = {
  UPLOAD_GALLERY: 'app/productcreate/UPLOAD_GALLERY',
  CREATE_PRODUCT: 'app/productcreate/CREATE_PRODUCT',
  UPDATE_PRODUCT: 'app/productcreate/UPDATE_PRODUCT',
  UPDATE_PRODUCT_GALLERY: 'app/productcreate/UPDATE_PRODUCT_GALLERY',
  UPLOAD_GALLERY_SUCCESS: 'app/productcreate/UPLOAD_GALLERY_SUCCESS',
  CREATE_PRODUCT_SUCCESS: 'app/productcreate/CREATE_PRODUCT_SUCCESS',
  UPDATE_PRODUCT_GALLERY_SUCCESS:
    'app/productcreate/UPDATE_PRODUCT_GALLERY_SUCCESS',
  RESET_PRODUCT_DATA: 'app/productcreate/RESET_PRODUCT_DATA',
  DELETE_PRODUCT_IMAGE: 'app/productcreate/DELETE_PRODUCT_IMAGE',
  UPDATE_PRODUCT_GALLERY_ORDER:
    'app/productcreate/UPDATE_PRODUCT_GALLERY_ORDER',
  UPDATE_PRODUCT_GALLERY_ORDER_SUCCESS:
    'app/productcreate/UPDATE_PRODUCT_GALLERY_ORDER_SUCCESS',
};
