/**
 * 
 * Profile action types
 * 
 */

 export const ActionTypes = {
   GET_ONE_PERFORMANCES_REQUEST: 'app/profile/GET_ONE_PERFORMANCES_REQUEST',
   GET_ONE_PERFORMANCES_SUCCESS: 'app/profile/GET_ONE_PERFORMANCES_SUCCESS',
   GET_ONE_PERFORMANCES_FAILURE: 'app/profile/GET_ONE_PERFORMANCES_FAILURE',
   RESET_PERFORMANCE: 'app/profile/RESET_PERFORMANCE',
   GET_FOLLOWERS_REQUEST: 'app/profile/GET_FOLLOWERS_REQUEST',
   GET_FOLLOWERS_SUCCESS: 'app/profile/GET_FOLLOWERS_SUCCESS',
   GET_FOLLOWERS_FAILURE: 'app/profile/GET_FOLLOWERS_FAILURE',
   GET_FOLLOWINGS_SUCCESS: 'app/profile/GET_FOLLOWINGS_SUCCESS',
   GET_FOLLOWINGS_REQUEST: 'app/profile/GET_FOLLOWINGS_REQUEST',
   GET_FOLLOWINGS_FAILURE: 'app/profile/GET_FOLLOWINGS_FAILURE',
   GET_PERFORMANCE_COUNT_REQUEST: '/app/profile/GET_PERFORMANCE_COUNT_REQUEST',
   GET_PERFORMANCE_COUNT_SUCCESS: '/app/profile/GET_PERFORMANCE_COUNT_SUCCESS',
   GET_PERFORMANCE_COUNT_FAILURE: '/app/profile/GET_PERFORMANCE_COUNT_FAILURE',
   GET_FOLLOWING_COUNT_REQUEST: '/app/profile/GET_FOLLOWING_COUNT_REQUEST',
   GET_FOLLOWING_COUNT_SUCCESS: '/app/profile/GET_FOLLOWING_COUNT_SUCCESS',
   GET_FOLLOWING_COUNT_FAILURE: '/app/profile/GET_FOLLOWING_COUNT_FAILURE',
   GET_FOLLOWER_COUNT_REQUEST: '/app/profile/GET_FOLLOWER_COUNT_REQUEST',
   GET_FOLLOWER_COUNT_SUCCESS: '/app/profile/GET_FOLLOWER_COUNT_SUCCESS',
   GET_FOLLOWER_COUNT_FAILURE: '/app/profile/GET_FOLLOWER_COUNT_FAILURE',
   GET_FIRST_PERFORMANCE_REQUEST: 'app/profile/GET_FIRST_PERFORMANCE_REQUEST',
   GET_FIRST_PERFORMANCE_SUCCESS: 'app/profile/GET_FIRST_PERFORMANCE_SUCCESS',
   GET_FIRST_PERFORMANCE_FAILURE: 'app/profile/GET_FIRST_PERFORMANCE_FAILURE',
   GET_USER_OTHER_INFO: 'app/profile/GET_USER_OTHER_INFO',
   SET_USER_OTHER_INFO: 'app/profile/SET_USER_OTHER_INFO',
 }